name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build on Arduino CLI
        run: bash .github/workflows/build-arduino.sh