#This file is used to command the pipeline. It holds stages
#which have spacific jobs. 

#inspiration: https://medium.com/swlh/how-to-create-an-automated-build-pipeline-for-your-arduino-project-1df9826f2a5e

name: build #stage name
on: #action to be triggered
  push:
  create:
  release:
    types: [published]


jobs: #define jobs
  
  build:
    runs-on: ubuntu-latest #github runner tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build on Arduino CLI
        run: bash .github/workflows/build-arduino.sh build-only #run the build file
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone AUniter
        run: git clone https://github.com/bxparks/AUniter.git tests/external/AUniter


      - name: Run unit tests on Arduino CLI
        run: bash .github/workflows/build-arduino.sh test-only